### ISSUE TITLE
Also set the Title of the PDF to the new filename

### ISSUE THREAD

**Issue by ad-si** [2mol/pboy#40]
Basically:
```sh
exiftool -Title="New filename" 123.pdf
```

**Comment by 2mol** [comment]
Done, I put it in the 1.4 branch as well. Thanks for the good idea!

If you're up for it you could add it as a config option, that would be super cool.

I made it so that it doesn't crash if `exiftool` is not installed (it's not on Mac), but then the command will just be ignored.

Will also have to add it to the changelog and remember to add it to the homebrew release.

**Comment by 2mol** [comment]
released in 1.4 thanks to #45
